language: nix
env:
  - ATTR=pip2nix.python27
  - ATTR=pip2nix.python36
  - ATTR=pip2nix.python37
  - ATTR=pip2nix.python38
  - ATTR=docs
  - MODE=bootstrap
script:
  - if [ -z "$MODE" ]; then nix-build release.nix -A $ATTR; fi
  - if [ "$MODE" == "bootstrap" ]; then
      ./bootstrap.sh && git --no-pager diff;
    fi
