name: "tests"
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        attr: [pip2nix.python27, pip2nix.python35, pip2nix.python36, pip2nix.python37, pip2nix.python38, docs, bootstrap]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: datakurre
    - run: if [ "${{ matrix.attr }}" != "bootstrap" ]; then nix-build release.nix -A ${{ matrix.attr }}; fi
    - run: if [ "${{ matrix.attr }}" == "bootstrap" ]; then ./bootstrap.sh && git --no-pager diff; fi
